version: '3'
services:
  message-processor:
    build: message_processor
    container_name: message-processor
    ports:
      - "8081:8081"
    environment:
      - STORAGE_SERVICE_URL=http://message-store:8082/store
    networks:
      - messaging-network
    depends_on:
      - message-store

  message-store:
    build: message_store
    container_name: message-store
    ports:
      - "8082:8082"
    environment:
      - MESSAGE_STORAGE_PATH=/data/messages
    volumes:
      - ./stored_messages:/data/messages
    networks:
      - messaging-network

networks:
  messaging-network:
    name: messaging-network

volumes:
  message-storage:
    name: message-storage